kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rb-scrum-team-hp
subjects:
  - kind: ServiceAccount
    name: sa-scrum-team-hp
    namespace: rbac
roleRef:
  kind: ClusterRole
  name: scrum-team-hp
  apiGroup: rbac.authorization.k8s.io
